modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/BotanyPots/issues"

[[mods]]
modId="botanypots"
updateJSONURL="https://updates.blamejared.com/get?n=botanypots&gv=1.15.2"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.botanypots]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.botanypots]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.botanypots]]
    modId="bookshelf"
    mandatory=true
    versionRange="[5.3.11,)"
    ordering="AFTER"
    side="BOTH"