modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/BotanyPots/issues"
license="LGPL v2.1"

[[mods]]
modId="botanypots"
updateJSONURL="https://updates.blamejared.com/get?n=botanypots&gv=1.16.5"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.botanypots]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.botanypots]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.botanypots]]
    modId="bookshelf"
    mandatory=true
    versionRange="[10,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.botanypots]]
    modId="crafttweaker"
    mandatory=false
    versionRange="[7.1,)"
    ordering="AFTER"
    side="BOTH"